
def test_no_NA_in_name_or_url():
    ...
    
def test_brand_col_added():
    ...
    
def id_col_added():
    ...
    
def test_no_racquets_containing_junior_in_name():
    ...
    
def test_no_cols_with_greater_95_pct_na():
    ...
    
def test_head_size_col_is_float():
    ...
    
def test_cleaned_data_is_proper_shape():
    ...